### ISSUE TITLE
PolyEugene - can't build on MAC

### ISSUE THREAD

**Issue by vcvrackideas** [RareBreeds/Orbits#2]
Hi! Just did a video about it and then realized that I can't compile it on mac, got some errors in orbitconfig file

**Comment by RareBreeds** [comment]
Thanks, I've just seen this issue raised but I think I fixed this yesterday whilst learning how to do the docker builds. The OrbitsConfig file was missing #include <array>.

**Comment by RareBreeds** [comment]
It should be fixed by this commit 650c624cf91513aa6631f45e499e2fd2bfb9526e. Thanks for trying out Polygene! Let me know if there's any issues, I'm planning on doing a release with it next week, once the vcp-59 challenge has ended as I don't want to risk breaking anything during it :).

**Comment by vcvrackideas** [comment]
no issues! only pure rhytmic fun I didn't know before, thank you! Hope you will see the video tomorrow. I've already prepared builds for people who will want to try it out before the release. Love the UI too, very attractive!
