### ISSUE TITLE
No Faceplate if username has non-ASCII characters

### ISSUE THREAD

**Issue by Petervos2018** [RareBreeds/Orbits#4]
Hi Mr. Breeds ( can I call you Rare ?)

Maybe this is of interest to you : 

https://community.vcvrack.com/t/rarebreeds-eugene-not-working/20266

Greetings Peter.

**Comment by RareBreeds** [comment]
I haven't validated this commit on a windows laptop yet. It doesn't seem to have broken anything on Mac at least.

**Comment by Petervos2018** [comment]
I'm just the bearer of bad news, 😄 I can't test anything because I have a "normal" username, but it's nice to see you're working on it.

**Comment by RareBreeds** [comment]
Yeah no worries, I'm setting up my wife's laptop to test it out. I suspect any path that has utf-8 characters would cause it so I'll just put my plugin in such a path and see if it reproduces. I suspect any plugin that uses the `json_load_file` function will suffer from this bug.

**Comment by RareBreeds** [comment]
This should be fixed in v2.0.3.
